name: optical_power_budget
description: A new Flutter project for calculating optical power budget.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

# flutter_launcher_icons configuration
# IMPORTANT: You must create a 1024x1024px icon and place it at the path below.
# For example: assets/icon/icon.png
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
